return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  event = 'VeryLazy',
  cmd = { 'TSUpdateSync', 'TSUpdate', 'TSInstall' },
  opts = {
    highlight = { enable = true },
    auto_install = true,
    sync_install = false,
    indent = { enable = true },
    endwise = { enable = true },
    ensure_installed = {
      'bash',
      'c',
      'diff',
      'dockerfile',
      'git_config',
      'gitignore',
      'html',
      'javascript',
      'jsdoc',
      'jsonc',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'query',
      'regex',
      'toml',
      'vim',
      'vimdoc',
      'xml',
      'yaml',
    },
  },
  config = function(_, opts)
    require('nvim-treesitter.configs').setup(opts)
  end,
}
